### ISSUE TITLE
Issue with using .cool file

### ISSUE THREAD

**Issue by Naveen-Ahuja** [dozmorovlab/TADCompare#16] opened 2023-05-20 18:38 UTC
Hello,

I followed the instructions provided here for working with .cool files https://bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/Input_Data.html

I converted my .cool files into a sparse 3-column matrix using HiCcompare::cooler2sparse and ran the TADCompare function but keep getting this error,

Converting to n x n matrix
Error in mat[rcix] <- sparse.mat[, 3] :
NAs are not allowed in subscripted assignments

I checked both my sparse matrices and there are no "NAs". Please let me know if I am doing something incorrectly.

When I show traceback this is what I get:
4.HiCcompare::sparse2full(cont_mat1)
3.TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]])
2.FUN(X[[i]], ...)
1.lapply(names(sparse_hgps_chr6), function(x) { TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]])
})

I get the exact same error when I use HiCcompare::cooler2sparse on my matrices for SpectralTAD

Thank you

**Comment by mdozmorov** [comment] 2023-05-20 23:01
It's likely the same issue as https://github.com/dozmorovlab/SpectralTAD/issues/7#issuecomment-1542432544. I'm looking into it.

**Comment by mdozmorov** [comment] 2023-05-20 23:04
It has been reported somewhere - I'm looking into it.

**Comment by Naveen-Ahuja** [comment] 2023-05-21 03:25
Thank you.

In the meantime, I also have hic pro files but they need to be merged and corrected, which I usually do by first converting them to .h5 files on HiC explorer and perform the rest on HiC explorer.

But since I want to use TADcompare would you recommend I convert it to another format or go about it another way?

Thanks

**Comment by mdozmorov** [comment] 2023-05-23 01:15
I would recommend merging the files before HiC-Pro, at the FASTQ files stage. Then, just import regularly, https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/Input_Data.html#working-with-hic-pro-files. Unnormalized data works well for boundary detection/comparison purposes, we described it in the SpectralTAD paper.

**Comment by Naveen-Ahuja** [comment] 2023-05-28 22:34
Oh, I see well actually the files I have were given to me and I don't have the raw fastq files.

Here is what I have done, HiC Pro converted using HiCExplorer --> .h5 --> merged bins --> ICE --> exported in Ginteractions on chr 6 --> loaded files into R.

Now I am not sure how to convert it into a sparse matrix looking at the vignette you provided.

Thank you for the help

**Comment by mdozmorov** [comment] 2023-05-29 01:31
All those formats are related because they represent the same information - pairs of interacting regions and the strength of interactions. GInteractions can be easily converted - assuming fixed resolution, just keep the start columns and the interaction frequency column.

**Comment by Naveen-Ahuja** [comment] 2023-06-01 19:08
Perfect, I got it to work now, thank you for your time and help I appreciate it.

**Comment by mdozmorov** [comment] 2023-06-06 00:23
About the original issue with cool files - does it still exist? It should be fixed, https://github.com/dozmorovlab/HiCcompare/issues/28

**Comment by Naveen-Ahuja** [comment] 2023-06-08 03:35
Hi,

I updated HiCcompare to v1.23.1 and still get the same error with .cool files,

```{r}
sparse_hgps_chr6 <- HiCcompare::cooler2sparse(hgps_chr6)
sparse_control_chr6 <- HiCcompare::cooler2sparse(control_chr6)
```

```{r}
diff_tads = lapply(names(sparse_hgps_chr6), function(x) {
  TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]])
})
```
Error in mat[rcix] <- sparse.mat[, 3] :
NAs are not allowed in subscripted assignments
4. HiCcompare::sparse2full(cont_mat1)
3. TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]])
2. FUN(X[[i]], ...)
1. lapply(names(sparse_hgps_chr6), function(x) {
TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]])
})

**Comment by mdozmorov** [comment] 2023-06-09 00:36
I'd need a reproducible example, data and code, to troubleshoot. Can you share?

**Comment by mdozmorov** [comment] 2023-07-10 00:47
Closing due to inactivity

**Closed as completed by mdozmorov** 2023-07-10 00:47 UTC

**Comment by Naveen-Ahuja** [comment] 2023-07-14 01:30
Hello,

Sorry for the delayed reply. I have attached the data and code that results in the error.

Data:

https://drive.google.com/drive/folders/1_1VYF8uLLfs4hH8DCYXMqiWPPyf7M5ob?usp=sharing

Code:

```{r}
hgps_chr6 <- read.table(file = '/Users/naveen/Desktop/Cool/HGPS_Chr1_Chr6.txt', header = FALSE, sep = '')
control_chr6 <- read.table(file = '/Users/naveen/Desktop/Cool/Control_Chr1_Chr6.txt', header = FALSE, sep = '')
```

```{r}
sparse_hgps_chr6 <- HiCcompare::cooler2sparse(hgps_chr6)
sparse_control_chr6 <- HiCcompare::cooler2sparse(control_chr6)
```

```{r}
diff_tads = lapply(names(sparse_hgps_chr6), function(x) {TADCompare(sparse_hgps_chr6[[x]], sparse_control_chr6[[x]]) 
})
```
Converting to n x n matrix
Error in mat[rcix] <- sparse.mat[, 3] : 
  NAs are not allowed in subscripted assignments

**Comment by mdozmorov** [comment] 2023-07-17 00:54
I can reproduce it and looking into it.

**Comment by mdozmorov** [comment] 2023-07-22 01:35
These files contain inter-chromosomal interactions, between chr1 and chr6. `cooler2sparse` will convert such data, but TADCompare was not designed to work with it. I filtered the data with commands like `awk '$1=="chr6" && $4=="chr6" {print $0}' HGPS_Chr1_Chr6.txt > HGPS_Chr6.txt`. 

There's still something wrong with the data, causing an issue with `HiCcompare::sparse2full()`. Can the data be incomplete? Please, let me know if filtering helps you.

**Comment by Naveen-Ahuja** [comment] 2023-07-29 02:55
I created new files with just a single chromosome so there should be no interchromosomal interactions now but the error is still persistent with HiCcompare::sparse2full(), here is the link to the single Chr files:

https://drive.google.com/drive/folders/1_1VYF8uLLfs4hH8DCYXMqiWPPyf7M5ob?usp=sharing

Could it be possible this has something to do with me using ICE correction, even though when I used ICE correction on GI file it worked fine with TADCompare.

**Comment by mdozmorov** [comment] 2023-07-29 11:49
ICE correction may be a problem. We recommend raw counts, the whole purpose of HiCcompare is to normalize them. That's what we provided the instructions for, https://www.bioconductor.org/packages/release/bioc/vignettes/HiCcompare/inst/doc/HiCcompare-vignette.html#extracting-data-from-.cool-files

The issues with cool files seem persistent, here's another one https://github.com/dozmorovlab/TADCompare/issues/17#issuecomment-1647823167. If @FlavianR can make a reproducible example, e.g., wget-ting the test files, processing them, then running the script, that'll speed things up. I'm traveling now but I'll get to it.
